#!/bin/sh


ZETTEL_DIR="${HOME}/.zettel"
ZETTELKAST_DIR="${ZETTEL_DIR}/zettelkast"
ZETTELKAST_TAGS_DIR="${ZETTEL_DIR}/tags"
ZETTELKAST_TAGS_DIR="${ZETTEL_DIR}/export"
ZETTEL_PREFIX=""
ZETTEL_POSTFIX=".$(date +%Y%m%d)"

cmd_usage ()
{
	# TODO
	:
}


# tag subcommand
cmd_tag ()
{
	case "$1" in
		help|--help)
			shift;
			cmd_usage $@
			;;
		create)
			shift;
			cd ${ZETTELKAST_TAGS_DIR}
			mkdir $@
			cd ${OLDPWD}
			;;
		rm)
			shift;
			cd ${ZETTELKAST_TAGS_DIR}
			rm -rf $@
			cd ${OLDPWD}
			;;
		rename)
			shift;
			cd ${ZETTELKAST_TAGS_DIR}
			mv $@
			cd ${OLDPWD}
			;;
		ls)
			shift;
			cd ${ZETTELKAST_TAGS_DIR}
			ls $@
			cd ${OLDPWD}
			;;
		note)
			shift;
			cd ${ZETTELKAST_TAGS_DIR}/$2
			ln -s ${ZETTELKAST_DIR}/$1
			cd ${OLDPWD}
			;;
		*)
			cmd_usage "$@"
			;;
	esac
}

# link subcommand
cmd_link ()
{
	cd ${ZETTELKAST_DIR}
	echo "related to: [$1]($1)" >> $2
	cd ${OLDPWD}
}

# main
echo 'note app' 1>&2

# if [ -d $NOTE_DIR ]
# 	echo 'create note directory' 1>&2
# 	mkdir ${NOTE_DIR}
# endif
#
# if [ -d $NOTE_DIR ]
# 	echo 'create zettelkast directory' 1>&2
# 	mkdir ${ZETTELKAST_DIR}
# endif


# TODO
#switch

case "$1" in
        help|--help)
		cmd_usage
		;;
        version|--version)
		echo ${VERSION}
		;;
        ls)
		shift;
		cd ${ZETTELKAST_DIR}
		ls $@
		cd ${OLDPWD}
		;;
        add)
		shift;
		$EDITOR ${ZETTELKAST_DIR}/${PREFIX}$1${POSTFIX}.md
		;;
        edit)
		shift;
		file="${ZETTELKAST_DIR}/${PREFIX}$1${POSTFIX}.md"
		if [ -f $file ]
		then
			$EDITOR $file
		else
			echo "Note does not exist."
		fi
		;;
        rm)
		shift;
		rm $ZETTELKAST_DIR/$1
		;;
        find)
		shift;
		find $ZETTELKAST_DIR -name "*$1*" -type f
		;;
        grep) shift;
		cd ${ZETTELKAST_DIR}
		grep $@
		cd ${OLDPWD}
        tag)
		shift;
		cmd_tag "$@";
		;;
        link)
		shift;
		echo "TODO"
		;;
        export)
		shift;
		echo "TODO"
		;;
        *)                              cmd_usage "$@" ;;
esac
exit 0
