#!/bin/sh


ZETTEL_DIR="${HOME}/.zettel"
ZETTELKAST_DIR="${ZETTEL_DIR}/zettelkast"
ZETTELKAST_TAGS_DIR="${ZETTEL_DIR}/tags"
ZETTELKAST_EXPORT_DIR="${ZETTEL_DIR}/export"
ZETTELKAST_DATA_DIR="${ZETTEL_DIR}/data"
ZETTEL_PREFIX=""
ZETTEL_POSTFIX=".$(date +%Y%m%d)"

cmd_usage ()
{
	# TODO
	:
}

# tag subcommand
cmd_data ()
{
	case "$1" in
		help|--help)
			shift;
			cmd_usage $@
			;;
		add)
			shift;
			cp $1 ${ZETTELKAST_DATA_DIR}
			;;
		rm)
			shift;
			cd ${ZETTELKAST_DATA_DIR}
			rm $@
			cd ${OLDPWD}
			;;
		rename)
			shift;
			cd ${ZETTELKAST_TAGS_DIR}
			mv $@
			cd ${OLDPWD}
			;;
		ls)
			shift;
			ls ${ZETTELKAST_DATA_DIR}
			;;
		*)
			cmd_usage "$@"
			;;
	esac
}

# tag subcommand
cmd_tag ()
{
	case "$1" in
		help|--help)
			shift;
			cmd_usage $@
			;;
		create)
			shift;
			cd ${ZETTELKAST_TAGS_DIR}
			mkdir $@
			cd ${OLDPWD}
			;;
		rm)
			shift;
			cd ${ZETTELKAST_TAGS_DIR}
			rm -rf $@
			cd ${OLDPWD}
			;;
		rename)
			shift;
			cd ${ZETTELKAST_TAGS_DIR}
			mv $@
			cd ${OLDPWD}
			;;
		ls)
			shift;
			cd ${ZETTELKAST_TAGS_DIR}
			ls $@
			cd ${OLDPWD}
			;;
		note)
			shift;
			cd ${ZETTELKAST_TAGS_DIR}/$2
			ln -s ${ZETTELKAST_DIR}/$1
			cd ${OLDPWD}
			;;
		*)
			cmd_usage "$@"
			;;
	esac
}

# main
echo 'note app' 1>&2

# if [ -d $NOTE_DIR ]
# 	echo 'create note directory' 1>&2
# 	mkdir ${NOTE_DIR}
# endif
#
# if [ -d $NOTE_DIR ]
# 	echo 'create zettelkast directory' 1>&2
# 	mkdir ${ZETTELKAST_DIR}
# endif


case "$1" in
        help|--help)
		cmd_usage
		;;
        version|--version)
		echo ${VERSION}
		;;
	init)
		cd ${ZETTEL_DIR}
		if [ -d .git]
		then
			git init
		fi
		;;
        ls)
		shift;
		cd ${ZETTELKAST_DIR}
		ls $@
		cd ${OLDPWD}
		;;
        add)
		shift;
		$EDITOR ${ZETTELKAST_DIR}/${ZETTEL_PREFIX}$1${ZETTEL_POSTFIX}.md
		;;
        edit)
		shift;
		file="${ZETTELKAST_DIR}/$1"
		if [ -f $file ]
		then
			$EDITOR $file
		else
			echo "Note does not exist."
		fi
		;;
        rm)
		shift;
		rm $ZETTELKAST_DIR/$1
		;;
        find)
		shift;
		find $ZETTELKAST_DIR -name "*$1*" -type f
		;;
        grep)
		shift;
		cd ${ZETTELKAST_DIR}
		grep $@
		cd ${OLDPWD}
		;;
        git)
		shift;
		cd ${ZETTEL_DIR}
		git $@;
		cd ${OLDPWD}
		;;
        data)
		shift;
		cmd_data "$@";
		;;
        tag)
		shift;
		cmd_tag "$@";
		;;
        link)
		shift;
		cd ${ZETTELKAST_DIR}
		echo "related to: [$1]($1)" >> $2
		cd ${OLDPWD}
		;;
        export)
		shift;
		echo "TODO"
		;;
        *)
		cmd_usage
		;;
esac
exit 0
